### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [NicknineTheEagle/TF2-Base#1]
Hello :D I have some suggestions that could help you not only you but all who use this Repo:

- Create an entry in the wiki that explains how to add a weapon or class etc. because of how TF2 works in your weapons and class creation system

- More comments in the code to explain how the code works

- Update the HUD in a behavioral sense, I explained to open the possibility of using hud customs

- Update the README.md showing the requirements that are needed not only to build the code but to run the same game

 hope it is to your liking :D

**Comment by NicknineTheEagle** [comment]
Regarding 3, no to that. Once again, this is supposed to be a straight port of the old version and updating HUD to be compatible with live TF2 would require a lot of modifications.
As for the rest, a proper documentation would be nice but writing it would be long and tedious process that I doubt I'll be able to get myself through.
