### ISSUE TITLE
Ambient Soundscapes Not Playing On Linux Server

### ISSUE THREAD

**Issue by Thornskade** [NicknineTheEagle/TF2-Base#13]
I'm not sure if I did something wrong, but when I join the server I host, outside areas are dead silent. When I create a local server, I hear environmental sounds outside, which I think are called soundscapes

**Comment by NicknineTheEagle** [comment]
Does the server console have any messages about missing files?

**Comment by Thornskade** [comment]
Oh yeah, it actually does, lol. `CSoundscapeSystem::Init:  Manifest 'scripts/soundscapes_manifest.txt' with bogus file type '', expecting 'file'`
I should have checked earlier

**Comment by Thornskade** [comment]
The file is there and not corrupt, so no idea

It says bogus file type, but I can't interpret that. I know Linux doesn't care for file extensions so the ".txt" is meaningless, but I also don't know what to do about it

As I downloaded the Multiplayer SDK directly from Steam using SteamCMD and verified it, it seems it's just "corrupt" on the servers as is

**Comment by NicknineTheEagle** [comment]
Steam servers are not the issue, the file is supposed to be a part of tf_port. You did download the server package listed on the latest release's page, right?

**Comment by Thornskade** [comment]
Certainly – I don't believe there's any other way I could have gotten a server up and running. But I couldn't find the file with a search, as I didn't realize it was included with the misc vpk, so I assumed it was referencing the hl2 folder instead

However, what I've seen just now is really strange. The vpk file in question always goes corrupt and fails to validate most files inside, including the soundscapes manifest.

I downloaded the zip to my Linux server directly and unzipped it there. -> The file is corrupt and won't validate
I downloaded the zip to my Windows PC and unzipped it there. -> The file validates
I uploaded the unzipped tf_port folder to my server. -> The file turns corrupt and won't validate

So it seems not matter what I do, the vpk files go corrupt simply by existing on a Linux server. What...?

Maybe I will try extracting the vpk files and upload everything as a simple folder structure instead.

**Comment by NicknineTheEagle** [comment]
That is really bizarre. What are you using to validate vpk files on Windows and Linux?

**Comment by Thornskade** [comment]
I use GCFScape. I don't know how to validate on my Linux server, what I do instead is download the file and check on my Windows PC. So if I upload the validated vpk to my server and then download it back from there, it is corrupt on Windows as well. And of course, the server can't use it either.

Well, I mean, given the server always throws that error message regarding the manifest file being a bogus file, I suppose in that sense the server is what I use to validate

**Comment by Thornskade** [comment]
Okay, so I extracted all the vpk contents into the folder structure and deleted the vpk files. The server still complains that the manifest file is bogus.

While I don't know why the vpk files go corrupt when transferring them between my desktop and the server, that whole thing appears to have been a red herring

**Comment by Thornskade** [comment]
So I searched up this problem and found these GitHub issues:
https://github.com/ValveSoftware/source-sdk-2013/pull/448
https://github.com/ValveSoftware/Source-1-Games/issues/2499

From what I can gather, the bug is on the Linux version of the Source Multiplayer 2013 SDK, or I guess it specifically has issues with Ubuntu, and this has nothing to do with this project

But other than that, that's all Chinese to me. I have no idea what they're saying so I don't know what to do to fix it

**Comment by NicknineTheEagle** [comment]
According to the linked posts, the issue is that Source SDK Base 2013 Dedicated Server ships with some outdated libraries on Linux. This post details the solution for that: https://github.com/ValveSoftware/source-sdk-2013/pull/448#issuecomment-371980998

**Comment by Thornskade** [comment]
Yes, as I said, but the solution is like it's written in a different language. I don't speak programmer, I can't code

I think they're saying I should go to the folder with the srcds or hl2 executable and then enter all that stuff they put in the box. But I'm not 100% sure and I'm always a little worried when someone tells me to put a lot of things in a terminal when I have no idea what it does

**Comment by NicknineTheEagle** [comment]
It's literally just a set of commands to put into Linux terminal, it's not even programming, have you never used Linux terminal before? The provided solution renames the bad outdated .so files and then creates symbolic links to proper ones in their place.
You can alternatively simply delete the outdated files and copy or rename the proper ones:
```
rm libtier0.so
cp libtier0_srv.so libtier0.so
rm libvstdlib.so
cp libvstdlib_srv.so libvstdlib.so
```

**Comment by Thornskade** [comment]
Obviously I have used the Linux terminal. Otherwise I doubt I'd be able to upkeep a server. I am still not inputting random commands that weren't explained. I don't know what "sync against" means or any of the other things which the person kept saying

What you say makes sense to me, the other person worded it really strangely to the point that I simply didn't understand it, so I didn't take the risk

**Comment by NicknineTheEagle** [comment]
Nice, I'll update README so that other people know about this required workaround.
