### ISSUE TITLE
Port for a free implementation of the engine.

### ISSUE THREAD

**Issue by ArtemS2** [NicknineTheEagle/TF2-Base#15]
Hello, I tried to submit your project to a free implementation of the source engine - https://github.com/nillerusr/source-engine.git. The results were very good for me, but I encountered 2 problems. 1) For some reason, all the 3rd person fighters move in T-poses. 2) Crash when capturing a point in point control mode. I will be very glad if you help me or tell me where to fix this. My repository with a port of your project - https://github.com/ArtemS2/source-engine-FCE/tree/tf2base

**Comment by ArtemS2** [comment]
![Снимок экрана от 2024-03-07 23-39-13](https://github.com/NicknineTheEagle/TF2-Base/assets/69766464/d7f0f8fb-82a3-482a-8036-930193553608)

**Comment by NicknineTheEagle** [comment]
This is outside of scope of this repository.
