### ISSUE TITLE
Spectator model issue

### ISSUE THREAD

**Issue by tryzombie501** [NicknineTheEagle/TF2-Base#2]
When spectating sometimes a player will just be displayed as their view model or completely invisible.
switching between thirdperson and firstperson spectate modes seems to cause and fix the issue.

**Comment by NicknineTheEagle** [comment]
Oh, yeah, I remember this. I know how to fix this but I can't figure out why this bug was not present in the original 2008 version.

**Comment by tryzombie501** [comment]
I never really noticed this bug until i started playing against rcbot2 bots. It was really distracting. Is it a simple issue to fix?

**Comment by NicknineTheEagle** [comment]
It's fairly simple but I gotta look into this more before doing anything.

**Comment by NicknineTheEagle** [comment]
Fixed in https://github.com/NicknineTheEagle/TF2-Base/commit/bf84b0b85a9da2de7179dff2a0be571d89496b39
