### ISSUE TITLE
Build fails with Visual Studio 2017

### ISSUE THREAD

**Issue by Margen67** [NicknineTheEagle/TF2-Base#3]
After getting past the `Unable to find RegKey for .vcproj files in solutions.` error from createtfmod.bat with [this solution](https://github.com/ValveSoftware/source-sdk-2013/issues/72#issuecomment-326633328), and upgrading 'Windows SDK Version' and 'Platform Toolset', and disabling treat warnings as errors, the build fails with about ~1k errors and ~3k warnings.

**Comment by NicknineTheEagle** [comment]
Of course, it fails, Valve have yet to update Source SDK to support VS 2017. There's nothing I can do here.

**Comment by Margen67** [comment]
@NicknineTheEagle Can I add you on Discord or Steam? I have a question.

**Comment by Margen67** [comment]
Possible workaround: https://github.com/ValveSoftware/source-sdk-2013/issues/72#issuecomment-326633328
