### ISSUE TITLE
Post 1.0.1.8 Features

### ISSUE THREAD

**Issue by tyabus** [NicknineTheEagle/TF2-Base#4]
There is any code that implements engineer's ability to move buildings leaked? Or that allows to upgrade non-sentrygun buildings?

**Comment by NicknineTheEagle** [comment]
This code base dates back to Jan 2008, it does not contain features from newer versions of the game and they will not be added. If you're asking if newer TF2 code has ever been leaked I can't help you with that.

**Comment by TorutheRedFox** [comment]
you can probably implement these features yourself

**Comment by NicknineTheEagle** [comment]
> you can probably implement these features yourself

Why did you post on a three year old closed issue?

**Comment by TorutheRedFox** [comment]
tbh idk lmao
