### ISSUE TITLE
build failed on visual studio 2013

### ISSUE THREAD

**Issue by stingrayking** [NicknineTheEagle/TF2-Base#8]
I even did the compile without any edit, but the build failed popped up. what's the problem?
with this error

Error	1	error C2220: warning treated as error - no 'object' file generated	c:\users\samsung\source\repos\tf2-base\src\vgui2\vgui_controls\buildgroup.cpp	1	1	vgui_controls
Warning	2	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\vgui2\vgui_controls\buildgroup.cpp	1	1	vgui_controls
Error	3	error C2220: warning treated as error - no 'object' file generated (BuildModeDialog.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	4	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (BuildModeDialog.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	5	error C2220: warning treated as error - no 'object' file generated (KeyValues.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	tier1
Warning	6	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyValues.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	tier1
Error	7	error C2220: warning treated as error - no 'object' file generated (CheckButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	8	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (CheckButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	9	error C2220: warning treated as error - no 'object' file generated (CheckButtonList.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	10	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (CheckButtonList.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	11	error C2220: warning treated as error - no 'object' file generated (snappy-stubs-internal.cpp)	c:\users\samsung\source\repos\tf2-base\src\tier1\snappy-stubs-internal.h	1	1	tier1
Warning	12	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (snappy-stubs-internal.cpp)	c:\users\samsung\source\repos\tf2-base\src\tier1\snappy-stubs-internal.h	1	1	tier1
Error	13	error C2220: warning treated as error - no 'object' file generated (snappy.cpp)	c:\users\samsung\source\repos\tf2-base\src\tier1\snappy-stubs-internal.h	1	1	tier1
Warning	14	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (snappy.cpp)	c:\users\samsung\source\repos\tf2-base\src\tier1\snappy-stubs-internal.h	1	1	tier1
Error	15	error C2220: warning treated as error - no 'object' file generated (ComboBox.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	16	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (ComboBox.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	17	error C2220: warning treated as error - no 'object' file generated (utlbinaryblock.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlbinaryblock.h	1	1	tier1
Warning	18	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (utlbinaryblock.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlbinaryblock.h	1	1	tier1
Error	19	error C2220: warning treated as error - no 'object' file generated (CvarToggleCheckButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	20	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (CvarToggleCheckButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	21	error C2220: warning treated as error - no 'object' file generated (utlbufferutil.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlbinaryblock.h	1	1	tier1
Warning	22	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (utlbufferutil.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlbinaryblock.h	1	1	tier1
Error	23	error C2220: warning treated as error - no 'object' file generated (EditablePanel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	24	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (EditablePanel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	25	error C2220: warning treated as error - no 'object' file generated (ExpandButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	26	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (ExpandButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	27	error C2220: warning treated as error - no 'object' file generated (Frame.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	28	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Frame.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	29	error C2220: warning treated as error - no 'object' file generated (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	30	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	31	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamtypes.h	1	1	vgui_controls
Warning	32	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamclientpublic.h	1	1	vgui_controls
Warning	33	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamuniverse.h	1	1	vgui_controls
Warning	34	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamutils.h	1	1	vgui_controls
Warning	35	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\matchmakingtypes.h	1	1	vgui_controls
Warning	36	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamuserstats.h	1	1	vgui_controls
Warning	37	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamremotestorage.h	1	1	vgui_controls
Warning	38	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (HTML.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamhttpenums.h	1	1	vgui_controls
Error	39	error C2220: warning treated as error - no 'object' file generated (Label.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	40	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Label.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	41	error C2220: warning treated as error - no 'object' file generated (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	42	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	43	error C2220: warning treated as error - no 'object' file generated (ListPanel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	44	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (ListPanel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	45	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamtypes.h	1	1	vgui_controls
Warning	46	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamclientpublic.h	1	1	vgui_controls
Warning	47	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamuniverse.h	1	1	vgui_controls
Warning	48	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamutils.h	1	1	vgui_controls
Warning	49	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\matchmakingtypes.h	1	1	vgui_controls
Warning	50	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamuserstats.h	1	1	vgui_controls
Warning	51	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamremotestorage.h	1	1	vgui_controls
Warning	52	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (KeyRepeat.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamhttpenums.h	1	1	vgui_controls
Error	53	error C2220: warning treated as error - no 'object' file generated (ListViewPanel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	54	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (ListViewPanel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	55	error C2220: warning treated as error - no 'object' file generated (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	56	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	57	error C2220: warning treated as error - no 'object' file generated	c:\users\samsung\source\repos\tf2-base\src\public\steam\steam_gameserver.h	1	1	Server (TF)
Warning	58	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\steam_gameserver.h	1	1	Server (TF)
Warning	59	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamtypes.h	1	1	Server (TF)
Warning	60	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamclientpublic.h	1	1	Server (TF)
Warning	61	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamuniverse.h	1	1	Server (TF)
Warning	62	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamutils.h	1	1	Server (TF)
Warning	63	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\matchmakingtypes.h	1	1	Server (TF)
Warning	64	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamuserstats.h	1	1	Server (TF)
Warning	65	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamremotestorage.h	1	1	Server (TF)
Warning	66	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamhttpenums.h	1	1	Server (TF)
Warning	67	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamtypes.h	1	1	vgui_controls
Warning	68	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamclientpublic.h	1	1	vgui_controls
Warning	69	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamuniverse.h	1	1	vgui_controls
Warning	70	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamutils.h	1	1	vgui_controls
Warning	71	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\matchmakingtypes.h	1	1	vgui_controls
Warning	72	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamuserstats.h	1	1	vgui_controls
Warning	73	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamremotestorage.h	1	1	vgui_controls
Error	74	error C2220: warning treated as error - no 'object' file generated (MenuItem.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	75	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (MenuItem.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	76	error C2220: warning treated as error - no 'object' file generated (MenuButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	77	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (MenuButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	78	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Menu.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamhttpenums.h	1	1	vgui_controls
Error	79	error C2220: warning treated as error - no 'object' file generated (Panel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	80	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Panel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	81	error C2220: warning treated as error - no 'object' file generated (QueryBox.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	82	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (QueryBox.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	83	error C2220: warning treated as error - no 'object' file generated (RadioButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	84	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RadioButton.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	85	error C2220: warning treated as error - no 'object' file generated (PropertySheet.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	86	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (PropertySheet.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	87	error C2220: warning treated as error - no 'object' file generated (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	88	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	89	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamtypes.h	1	1	vgui_controls
Warning	90	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamclientpublic.h	1	1	vgui_controls
Warning	91	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamuniverse.h	1	1	vgui_controls
Warning	92	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamutils.h	1	1	vgui_controls
Warning	93	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\matchmakingtypes.h	1	1	vgui_controls
Warning	94	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamuserstats.h	1	1	vgui_controls
Warning	95	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\isteamremotestorage.h	1	1	vgui_controls
Warning	96	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (RichText.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\steam\steamhttpenums.h	1	1	vgui_controls
Error	97	error C2220: warning treated as error - no 'object' file generated (SectionedListPanel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	98	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (SectionedListPanel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	99	error C2220: warning treated as error - no 'object' file generated (Slider.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	100	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (Slider.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	101	error C2220: warning treated as error - no 'object' file generated (TextImage.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	102	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (TextImage.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	103	error C2220: warning treated as error - no 'object' file generated (TreeView.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	104	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (TreeView.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	105	error C2220: warning treated as error - no 'object' file generated (TreeViewListControl.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	106	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (TreeViewListControl.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	107	error C2220: warning treated as error - no 'object' file generated (URLLabel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Warning	108	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss (URLLabel.cpp)	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	vgui_controls
Error	109	error C2220: warning treated as error - no 'object' file generated	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlbinaryblock.h	1	1	Client (TF)
Warning	110	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlbinaryblock.h	1	1	Client (TF)
Warning	111	warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	c:\users\samsung\source\repos\tf2-base\src\public\tier1\utlsortvector.h	1	1	Client (TF)

**Comment by NicknineTheEagle** [comment]
Uh, apparently, VGUI files contain a character that can't be represented in Korean code page (Windows-949)? I have no idea what it could be cause VS doesn't even mention the line where it is.
The only advice I can give is try changing your system default code page: https://forums.asp.net/t/1134534.aspx.

**Comment by stingrayking** [comment]
Ok thank you for anwser

**Comment by NicknineTheEagle** [comment]
I assumed this is fixed, closing.
