### ISSUE TITLE
What's wrong with this?

### ISSUE THREAD

**Issue by stingrayking** [NicknineTheEagle/TF2-Base#9]
When I launch the game, this [<a href="https://ibb.co/ngGVKSh"><img src="https://i.ibb.co/xCkcrQV/Team-Fortress-2-1-0-1-8-Port-2021-09-12-9-32-27.png" alt="Team-Fortress-2-1-0-1-8-Port-2021-09-12-9-32-27" border="0"></a>] suddenly pops up.
If you choose break in debugger, the game crashes
If you choose "ingore this assert," it seems to work correctly. but.. when you load a map, the game crashes again.
what is this problem? and how can i solve this?

**Comment by NicknineTheEagle** [comment]
Post the crash dump (should be in Steam\dumps) or at least show where it crashes, I'm not a mind reader.

**Comment by stingrayking** [comment]
> Post the crash dump (should be in Steam\dumps) or at least show where it crashes, I'm not a mind reader.
https://drive.google.com/file/d/1eqxpEQbNuuwPSxf1WLGsRsEr2v28hL9C/view?usp=sharing  here

**Comment by NicknineTheEagle** [comment]
What was the issue?

**Comment by stingrayking** [comment]
> What was the issue?

It was solved when the default system Unicode was changed to the america

**Comment by NicknineTheEagle** [comment]
Ah, so same issue as last time. I see.
